#### Problem Statement 1: 
Write a function so that the columns of the output matrix are powers of the input
vector.The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [1]:
import numpy as np

In [2]:
### Create Function for calculating require matrix
def alexandre_Vandermonde(mat,n, increasing=False):
    if not increasing:
        mat = [[item**(i-1) for i in range(n,0,-1)] for item in mat]
    else:
        mat = [[item**i for i in range(0,n)] for item in mat]
    return mat

In [3]:
R = int(input("Enter the number of rows:")) 
N = int(input("Enter the number of Columns: "))
matrix = []
for i in range(R):
    matrix.append(int(input()))

print("The Result are in decreasing order:")
print(np.array(alexandre_Vandermonde(matrix,N, increasing=False)))
print("The Result are in increasing order:")
print(np.array(alexandre_Vandermonde(matrix,N, increasing=True)))

Enter the number of rows:5
Enter the number of Columns: 4
1
2
3
4
5
The Result are in decreasing order:
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
The Result are in increasing order:
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]


#### Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i      1  2  3  4  5  6  7  8  9  10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
### Create function
def solve(my_list, window_size): ## take right arugment
    new_list=[]
    for i in range(len(my_list)-2):   ### only till length-2
        sum = 0
        for item in my_list[i:window_size+i]:  ## traverse only 
            sum = sum + item
        new_list.append(sum/window_size)    ## appending into new_list
    return np.array(new_list).round(2)

In [5]:
window_size = 3
sample_list = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
solve(sample_list,window_size)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])